# Generated by Django 5.2.8 on 2025-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACAO", "Ação"),
                            ("FII", "Fundo Imobiliário"),
                            ("RENDA_FIXA", "Renda Fixa"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
