# Generated by Django 5.2.8 on 2025-11-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("portifolios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "preco_medio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.asset"
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="portifolios.portfolio",
                    ),
                ),
            ],
        ),
    ]
